// Code generated by "stringer -type=BerthState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BS_OPEN-0]
	_ = x[BS_CLOSED-1]
	_ = x[BS_OCCUPIED-2]
	_ = x[BS_RESERVED-3]
}

const _BerthState_name = "BS_OPENBS_CLOSEDBS_OCCUPIEDBS_RESERVED"

var _BerthState_index = [...]uint8{0, 7, 16, 27, 38}

func (i BerthState) String() string {
	if i < 0 || i >= BerthState(len(_BerthState_index)-1) {
		return "BerthState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BerthState_name[_BerthState_index[i]:_BerthState_index[i+1]]
}
