// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[D_SHIP_ARRIVAL-0]
	_ = x[D_SHIP_BERTHING-1]
	_ = x[D_SHIP_LAUNCHING-2]
	_ = x[D_TUG_AVAILABLE-3]
	_ = x[D_BERTH_OCCUPIED-4]
	_ = x[D_BERTH_EMPTY-5]
	_ = x[D_SHIP_ASSIGNED-6]
	_ = x[D_UNLOADING_DONE-7]
	_ = x[S_ATTACH-8]
	_ = x[S_DETACH-9]
	_ = x[S_BERTH-10]
	_ = x[S_LAUNCH-11]
	_ = x[S_ASSIGN-12]
	_ = x[S_TUG_ASSIGN-13]
	_ = x[T_SHIP-14]
	_ = x[T_DETACH-15]
	_ = x[T_GO-16]
	_ = x[B_DOCK-17]
	_ = x[B_UNDOCK-18]
	_ = x[B_RESERVE-19]
}

const _EventType_name = "D_SHIP_ARRIVALD_SHIP_BERTHINGD_SHIP_LAUNCHINGD_TUG_AVAILABLED_BERTH_OCCUPIEDD_BERTH_EMPTYD_SHIP_ASSIGNEDD_UNLOADING_DONES_ATTACHS_DETACHS_BERTHS_LAUNCHS_ASSIGNS_TUG_ASSIGNT_SHIPT_DETACHT_GOB_DOCKB_UNDOCKB_RESERVE"

var _EventType_index = [...]uint8{0, 14, 29, 45, 60, 76, 89, 104, 120, 128, 136, 143, 151, 159, 171, 177, 185, 189, 195, 203, 212}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
